/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminSuggestionsModal: typeof import('./src/components/profile/AdminSuggestionsModal.vue')['default']
    AiAnalysisCard: typeof import('./src/components/AiAnalysisCard.vue')['default']
    AnalysisBody: typeof import('./src/components/AnalysisBody.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    ChatInputBox: typeof import('./src/components/chat/ChatInputBox.vue')['default']
    ChatMessageItem: typeof import('./src/components/chat/ChatMessageItem.vue')['default']
    ChatSidebar: typeof import('./src/components/chat/ChatSidebar.vue')['default']
    ChatStreamingItem: typeof import('./src/components/chat/ChatStreamingItem.vue')['default']
    CheckinButton: typeof import('./src/components/CheckinButton.vue')['default']
    CollectionModal: typeof import('./src/components/collection/CollectionModal.vue')['default']
    DiaryComposer: typeof import('./src/components/DiaryComposer.vue')['default']
    DiaryFeedItem: typeof import('./src/components/DiaryFeedItem.vue')['default']
    GlobalConsolidationModals: typeof import('./src/components/GlobalConsolidationModals.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    LifeChapterContent: typeof import('./src/components/LifeChapterContent.vue')['default']
    LoadingSkeleton: typeof import('./src/components/LoadingSkeleton.vue')['default']
    MemoryGraphView: typeof import('./src/components/memory/MemoryGraphView.vue')['default']
    MemoryProfileView: typeof import('./src/components/memory/MemoryProfileView.vue')['default']
    MusicCard: typeof import('./src/components/MusicCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    ProfileSearchPanel: typeof import('./src/components/profile/ProfileSearchPanel.vue')['default']
    ProfileSettingsModal: typeof import('./src/components/profile/ProfileSettingsModal.vue')['default']
    PublicFeed: typeof import('./src/components/PublicFeed.vue')['default']
    PullToRefresh: typeof import('./src/components/PullToRefresh.vue')['default']
    QuotaTableModal: typeof import('./src/components/QuotaTableModal.vue')['default']
    ReferenceBar: typeof import('./src/components/ReferenceBar.vue')['default']
    ReportCharts: typeof import('./src/components/ReportCharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingSection: typeof import('./src/components/SettingSection.vue')['default']
    SimilarDiariesPanel: typeof import('./src/components/SimilarDiariesPanel.vue')['default']
  }
}
