const fs = require('fs');
let code = fs.readFileSync('d:/Code/MoodCopilot/frontend/src/components/profile/ProfileSettingsModal.vue', 'utf8');

code = code.replace(/auth\.displayName\?\.charAt\(0\) \|\| '\?'/g, "auth.displayName?.charAt(0) || '我'");
code = code.replace(/<SettingSection title="用户\?" tag="Identity">/g, '<SettingSection title="用户名" tag="Identity">');
code = code.replace(/<SettingSection title="个性签\?" tag="Profile">/g, '<SettingSection title="个性签名" tag="Profile">');
code = code.replace(/placeholder="写一句你希望别人看到的状态（最\?60字）"/g, 'placeholder="写一句你希望别人看到的状态（最多160字）"');
code = code.replace(/<p class="settings-desc">邮箱账号当前仅用于登录和安全验证，暂不支持直接修改\?\/p>/g, '<p class="settings-desc">邮箱账号当前仅用于登录和安全验证，暂不支持直接修改。</p>');
code = code.replace(/<SettingSection title="提醒与陪\?" tag="Routine">/g, '<SettingSection title="提醒与陪伴" tag="Routine">');
code = code.replace(/<p class="settings-desc">修改密码前会向当前账号邮箱发送验证码，验证通过后才会生效\?\r?\n\/p>/g, '<p class="settings-desc">修改密码前会向当前账号邮箱发送验证码，验证通过后才会生效。</p>');
code = code.replace(/<p class="settings-desc">修改密码前会向当前账号邮箱发送验证码，验证通过后才会生效\?<\/p>/g, '<p class="settings-desc">修改密码前会向当前账号邮箱发送验证码，验证通过后才会生效。</p>');
code = code.replace(/placeholder="再次输入新密\?"/g, 'placeholder="再次输入新密码"');
code = code.replace(/placeholder="输入邮箱验证\?"/g, 'placeholder="输入邮箱验证码"');
code = code.replace(/<SettingSection title="请开发者喝杯奶\?" tag="🧋" extraClass="support-donate-section">/g, '<SettingSection title="请开发者喝杯奶茶" tag="🧋" extraClass="support-donate-section">');
code = code.replace(/去看\?\?/g, '去看看 →');
code = code.replace(/<SettingSection title="建议与反\?" tag="Feedback">/g, '<SettingSection title="建议与反馈" tag="Feedback">');
code = code.replace(/<n-button type="error" block @click="handleLogout">退出登\?\/n-button>/g, '<n-button type="error" block @click="handleLogout">退出登录</n-button>');
code = code.replace(/<n-button size="small" @click="zoomOut">\?\/n-button>/g, '<n-button size="small" @click="zoomOut">−</n-button>');
code = code.replace(/<n-button size="small" @click="zoomIn">\?\/n-button>/g, '<n-button size="small" @click="zoomIn">＋</n-button>');
code = code.replace(/\{ value: 'starlight-blue', label: '星光\?', primary: '#41BBC8', bg: '#FCF9E8' \},/g, "{ value: 'starlight-blue', label: '星光蓝', primary: '#41BBC8', bg: '#FCF9E8' },");
code = code.replace(/\{ value: 'bamboo-moon', label: '竹月\?', primary: '#6090B8', bg: '#F3D8C3' \},/g, "{ value: 'bamboo-moon', label: '竹月色', primary: '#6090B8', bg: '#F3D8C3' },");
code = code.replace(/\{ value: 'pine-cone', label: '松果\?', primary: '#664B3A', bg: '#DBC6B4' \}/g, "{ value: 'pine-cone', label: '松果褐', primary: '#664B3A', bg: '#DBC6B4' }");
code = code.replace(/window\.\\?\.error\('提交失败\?' \+ \(err\.response\?\.data\?\.message \|\| err\.message\)\)/g, "window..error('提交失败：' + (err.response?.data?.message || err.message))");
code = code.replace(/uploadMsg\.value = '头像已更\?'/g, "uploadMsg.value = '头像已更新'");
code = code.replace(/需\?2-20 位中英文、数字、下划线\r?\n或横\?/g, '需为 2-20 位中英文、数字、下划线或横线');
code = code.replace(/需\?2-20 位中英文、数字、下划线或横\?/g, '需为 2-20 位中英文、数字、下划线或横线');
code = code.replace(/logWarn\('profile', '检查用户名可用性失\?', name, e\)/g, "logWarn('profile', '检查用户名可用性失败', name, e)");
code = code.replace(/passwordMsg\.value = e\?\.response\?\.data\?\.message \|\| '验证码发送失\?'/g, "passwordMsg.value = e?.response?.data?.message || '验证码发送失败'");
code = code.replace(/passwordMsg\.value = '请输入当前密\?'/g, "passwordMsg.value = '请输入当前密码'");
code = code.replace(/passwordMsg\.value = '新密码至\?6 \?'/g, "passwordMsg.value = '新密码至少 6 位'");
code = code.replace(/passwordMsg\.value = '两次输入的新密码不一\?'/g, "passwordMsg.value = '两次输入的新密码不一致'");

fs.writeFileSync('d:/Code/MoodCopilot/frontend/src/components/profile/ProfileSettingsModal.vue', code, 'utf8');
