ALTER TABLE diary_resonances ADD COLUMN message VARCHAR(200) NULL AFTER created_at;
ALTER TABLE notifications MODIFY COLUMN type ENUM('COMMENT','REPLY','RESONANCE','SYSTEM','FOLLOW','ENCOURAGEMENT') NOT NULL;
